### ISSUE TITLE
cap-request publish custom post but not regular post

### ISSUE THREAD

**Issue by liquido** [thenbrent/map-cap#3]
is there a way how a user can publish a custom post, but not "regular" posts? at the moment, publishing custom posts only goes along with publish_post... I would like custom posts to be used and published by registered users and publish news-articles (regular) articles) only by myself or admin-staff. This would be usefull for many sites I'm administrating and as well for Wordpress as a CMS with a team running it.

**Comment by thenbrent** [comment]
Yep, that's exactly what this plugin does. 

Install it, then set which roles can publish custom posts under _Settings | Map Cap_ of the admin menu.

http://wordpress.org/extend/plugins/map-cap/

**Comment by liquido** [comment]
Well... every time I give a role the custom-post-publish-cap, this role is also granted the publish_post-cap (which is unwanted)

**Comment by liquido** [comment]
I use WP 3.0.1 and the actual version of map-cap (installed today via backend)

**Comment by thenbrent** [comment]
Are you giving the users you don't want publishing posts the subscriber role? Contributor roles and above have the publish post capability. 

Otherwise, it could be a bug and will need some tracking down as I've not seen it on any other site. You can download Justin Tadlock's "Members" plugin to confirm if Map Cap is actually giving subscribers the publish_post capability when giving them publish_custom_post capability.
